services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      # ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      # DATABASE_URL: ${DATABASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      AFRICASTALKING_API_KEY: ${AFRICASTALKING_API_KEY}
      AFRICASTALKING_USERNAME: ${AFRICASTALKING_USERNAME}
      AFRICASTALKING_SENDERID: ${AFRICASTALKING_SENDERID}
      Token_URL: ${Token_URL}
      REDIRECT_URI: ${REDIRECT_URI}
      Auth_URL: ${Auth_URL}
      Auth_Provider: ${Auth_Provider}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/app:z
    networks:
      - sil_network

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - sil_network
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  sil_network:
    external: true
