name: Django API Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 3784
          POSTGRES_DB: savannah2_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DB_NAME: savannah2_test
          DB_USER: postgres
          DB_PASSWORD: 3784
          DB_HOST: localhost
          DB_PORT: 5432
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID || '' }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET || '' }}
          AFRICASTALKING_USERNAME: sandbox
          AFRICASTALKING_API_KEY: ${{ secrets.AFRICASTALKING_API_KEY || 'test_key' }}
          AFRICASTALKING_SENDERID: SAVANNAHAPI
        run: |
          python -m pytest api -v
